short-url/config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  resources :users, only: [:index, :new, :create] do
    member do
      resources :urls, only: [:index, :new, :create, :show, :destroy]
    end
  end

end

short-url/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

short-url/app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user

  validates :long_url, presence: true

  before_create :generate_short_url, :sanitize

  def generate_short_url
    rand(36**8).to_s(36)
  end

  def sanitize
    long_url.strip!
    sanitize_url = self.long_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    "http://#{sanitize_url}"
  end

end

short-url/app/models/user.rb
class User < ApplicationRecord
  has_many :urls
end

short-url/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

short-url/app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.where(user_id: params[:id])
  end

  def new
    @user = User.find(params[:id])
    @url = Url.new
  end

  def create
    url = Url.new(url_params)
    url.short_url = url.generate_short_url
    url.long_url = url.sanitize
    if url.save
      redirect_to urls_path
    else
      flash[:error] = url.errors.full_messages
      redirect_to new_url_path
    end
  end

  def show
    @url = Url.find_by(short_url: params[:short_url])
    redirect_to @url.sanitize
  end

  def destroy
    @url = Url.find_by(params[:id])
    @url.delete
    redirect_to urls_path
  end

  private
  def url_params
    params.require(:url).permit(:name,:long_url,:user_id, :category_id)
  end
end

short-url/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username)
  end

end

short-url/app/helpers/application_helper.rb
module ApplicationHelper
end

short-url/app/helpers/urls_helper.rb
module UrlsHelper
end

short-url/app/helpers/users_helper.rb
module UsersHelper
end

short-url/app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <p> @Copyright  2022 - All Right Reserved.</p>
    <p><a href="mailto:hege@example.com">abc@example.com</a></p>
  </div>
</footer>

short-url/app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <h2>Shorten Url</h2>
  </div>
</header>

short-url/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag "short-url.css" %>
  </head>
  <body>
      <%=  render "layouts/header"%>
        <%= yield %>
      <%=  render "layouts/footer"%>
  </body>
</html>

short-url/app/views/urls/index.html.erb
<h2>Url List</h2>
<div class="w3-container">
  <div class="w3-ul w3-card" style="width:80%">
    <% if @urls.size > 0 %>
      <% @urls.each do |url| %>
        <li class="w3-display-container">
          <%= url.name %>
          <%= link_to url.short_url, url.long_url %>
        </li>
      <% end %>
    <% end %>
  </div><br>
  <%= link_to 'Create a link', new_url_path(@urls.first.user), class:'button'%>
  <%= link_to 'Back', root_path, class:'button'%>


</div>

short-url/app/views/urls/new.html.erb
<%= flash[:error] %>
<div class="form_content">
  <p><b><%= @user.username %></b> Create Long Url </p>
  <%= form_with model: @url do |form| %>
  <%= form.label :'name of url' %><br>
  <%= form.text_field :name %><br><br>
  <%= form.label :'input url you want to shorten:' %><br>
  <%= form.text_field :long_url %><br><br>
  <%= form.hidden_field :user_id, value: @user.id %>
  <%= form.submit %>
<% end %>
</div>

short-url/app/views/users/index.html.erb
<h2>Users List</h2>
<% if @users.size > 0 %>
<div class="w3-container">
    <div class="w3-ul w3-card" style="width:80%">
        <% @users.each do |user| %>
          <li class="w3-display-container">
            <%= user.username %>
            <%= link_to 'Create a link', new_url_path(user) %>
          </li>
        <% end %>
    </div><br>
</div>
<% else %>
  <h3>No Users!! create a User</h3>
<% end %>
<div class="User-button">
<%= link_to 'Create User', new_user_path, class: 'button' %>
</div>

short-url/app/views/users/new.html.erb
<div class="form_content">
  <%= form_with model: @user do |form| %>
    <%= form.label :'Please enter your username' %><br><br>
    <%= form.text_field :username %><br><br>
    <%= form.submit %>
<% end %>
</div>